### ISSUE TITLE
menu is not triggered in tmux 3.0a

### ISSUE THREAD

**Issue by creinig** [jaclu/tmux-menus#2]
In tmux 3.0a (stock version in Ubuntu 20.04 LTS) the menu is not triggered by the keystroke. The reason seems to be that in that version, `tmux bind-key` does not support the `-N`option:
```
> ./menus.tmux 
tmux: unknown option -- N
usage: bind-key [-cnr] [-T key-table] key command [arguments]
```

When removing the option (and its argument) from the call in `menus.tmux` everything works fine.

**Comment by datamadsen** [comment]
Thank you @creinig - this was driving me crazy.

**Comment by jaclu** [comment]
Ooops, my bad will remove all -N bindings

**Comment by jaclu** [comment]
It should be fixed now, ideally let me know and close it (you should be able to I think) otherwise I will close it
