### ISSUE TITLE
Shortcut key priority

### ISSUE THREAD

**Issue by ndsizeif** [jaclu/tmux-menus#20]
Thank you for providing this tool.  

### issue:
I noticed that lower case 'j' and 'k' function as vi-keys and are enabled by default 
in a tmux menu. Binding menu shortcut commands to 'j' or 'k' can result in an 
unexpected action during navigation.

### example:
The Advanced Options and Handling Sessions menu have Kill server and kill current 
session bound to k out of the box. Attempting to navigate up in either menu with 
the 'k' key will result in a prompt to kill a session(s). 

### suggestion:
It may help to avoid using those two keys as bindings in the stock menus for new 
users of the plugin.

**Comment by jaclu** [comment]
Change applied! By all means re-open if more needs to be added to this issue! Otherwise thx for some good feedback!
