### ISSUE TITLE
https://ifconfig.me instead of ifconfig.me

### ISSUE THREAD

**Issue by wilddog64** [jaclu/tmux-menus#26]
Appearently that curl ifconfig.me does not return a correct public id address. One has to use https://ifconfig.me to return corrrect one

**Comment by jaclu** [comment]
Sorry for the late response, I missed the notification :(
I use macOS and Linux, and for them either notation works,  so I am a bit curious about what environment it fails in.
According to the curl man page, it will try until it finds a working protocol, so shouldn't normally fail for you, however, one advantage of giving the https: // prefix is that it will reduce the resources spent figuring out the protocol. Either way, I added your change, thx for the update!

**Comment by wilddog64** [comment]
I am a Mac user. I am not sure why it returns a different IP address in
different ways. Under zsh shell I use this to find my public ip address:

dig +short myip.opendns.com @resolver1.opendns.com

This is how I find out yours are different.

Anyway, thank you for a quick response and fix the problem.

Wildddog64
