### ISSUE TITLE
OMG

### ISSUE THREAD

**Issue by Azulinho** [jaclu/tmux-menus#27]
I love you

How on earth I didn't know I needed this?

it's that first iPod feeling all over again

u'da'best

( I will no longer have to google for show status, when my status line goes AWOL)

**Comment by jaclu** [comment]
If you figure out any other features that you think would make sense, just mention them and I add them

**Comment by jaclu** [comment]
I just realized I hadn't added toggle status to the menus, now it is available in the main menu - thx for the suggestion, though Im a bit confused as to why you listed a missing feature as something you appreciated with the menus :)
