### ISSUE TITLE
Add setting for tmux.conf

### ISSUE THREAD

**Issue by axman6** [jaclu/tmux-menus#32]
The reload config item defaults to `~/.tmux.conf`, though the world seems to be moving to using `$XDG_CONFIG_HOME/tmux/tmux.conf` (a.k.a `~/.config/tmux/tmux.conf` usually). It would be nice to be able to set this instead of typing it every time (or if possible, inferring it from the current tmux session, but I don't know if that' possible).

**Comment by jaclu** [comment]
makes sense, will do it a config item within a day or so

**Comment by jaclu** [comment]
I have updated this to support the requested feature, check the README and search for "Pointer to config file" for details.
