### ISSUE TITLE
How to unbind `\`?

### ISSUE THREAD

**Issue by Erimus-Koo** [jaclu/tmux-menus#33]
I tried `unbind \` and `unbind-key \` but not work.
And in my case, `prefix + \` does not work for me, right-click works.

**Comment by jaclu** [comment]
Either '\' or without quotes as \\

**Comment by Erimus-Koo** [comment]
I've tried but still nothing changed

**Comment by jaclu** [comment]
I just tried and this worked for me: `tmux unbind \\` This disabled the default shortcut
I am running tmux 3.3a, If you run some other version, please let me know and I will investigate if this procedure does not work for that version

**Comment by Erimus-Koo** [comment]
I got it.

My previous mistake is about the order.

1. Bind `\` to split pane
2. Set plugins (I thought this step means import)
3. Then unbind (Canceled my own bind function)

And now changed to
1. unbind
2. bind
3. set plugin (Looks it works only on install, and will import at the very first before step 1)
