### ISSUE TITLE
wrong path to utils.sh if there is a third level like in Extras scripts

### ISSUE THREAD

**Issue by dashorty** [jaclu/tmux-menus#39]
If I run the spotify script from the menu then the `dialog_handling.sh` cannot find den `utils.sh` because there is one more layer.

output from `dialog_handling.sh`:
```shell
CURRENT_DIR: /home/dashorty/.tmux/plugins/tmux-menus/items/extras
SCRIPT_DIR : /home/dashorty/.tmux/plugins/tmux-menus/items/scripts
``` 
https://github.com/jaclu/tmux-menus/blob/7a388b5f9eff159fc79e629112e7d567332cb921/scripts/dialog_handling.sh#L436-L443

**Comment by jaclu** [comment]
I tested it on several systems, so the checks should hopefully work on all platforms! Im closing this now, but please re-open if the issue was not resolved!
