### ISSUE TITLE
Menu caching broken in read-only file system

### ISSUE THREAD

**Issue by JuanGarcia345** [jaclu/tmux-menus#41]
Hi there,

First of all, thanks for this really nice piece of software.

Menu caching as added by merge request #40 makes the assumption that plugin directory is writable. Unfortunately, this is not the case for configuration managers such as [home manager](https://github.com/nix-community/home-manager). Is there any way to deactivate menu caching or to change this cache directory?

Thank you!

**Comment by jaclu** [comment]
Good point, will try to make it an option

**Comment by jaclu** [comment]
btw, in the meantime, you could soft-link the location for tmux-menus to a writeable folder, assuming there is such a thing. If you are on a pure read-only FS that unfortunately not  help

**Comment by JuanGarcia345** [comment]
Good idea, I'll look into it. Thanks a lot for your reply

**Comment by jaclu** [comment]
Added branch no_cache, which seems to work fine, on both Linux and MacOS 

Disable caching by adding: `set -g @menus_use_cache 'no'` to your tmux.conf

Let me know if this works in your env!

**Comment by JuanGarcia345** [comment]
Neat! It worked as expected, thank you
