### ISSUE TITLE
Integrate with popular themes like Catppuccin

### ISSUE THREAD

**Issue by thomastthai** [jaclu/tmux-menus#47]
Some people, like me, use popular theme plugins like Catppuccin for colors and glyphs to give a consistent look for tmux and neovim sessions. Allowing for easy integration with such themes would help promote that consistent look.

**Comment by jaclu** [comment]
Ill need to check them up first to get a better understanding of what you are suggesting, ill get back to this in a couple of days :)

**Comment by jaclu** [comment]
After giving it some thought I think adding theme support is a great idea!

I have set up a branch: layout where this is added, if you have time/energy I would really appreciate if you could try it out and let me know if this is in the right direction

**Comment by jaclu** [comment]
I updated the main menu to have all the overrides pre-defined and commented out, to make it easier to play around with it, and I also expanded the Styling page a bit, to hopefully better explain things
